import { Molecule, MoleculeCategory } from './types';

export const MOLECULES: Molecule[] = [
  {
    id: '1',
    name: 'Molécula 962',
    formula: 'Compound 962',
    category: MoleculeCategory.ORGANIC,
    searchQuery: 'molecule 962 3d',
    modelPath: '/models/962-CPK-color-print_NIH3D.glb',
    description: 'Modelo molecular 3D real do NIH 3D Print Exchange.',
    modelVariants: {
      cpk: '/models/962-CPK-color-print_NIH3D.glb',
      bas: '/models/962-bas-color-print_NIH3D.glb',
      sticks: '/models/962-sticks-color-vis_NIH3D.glb',
    },
  },
  {
    id: '2',
    name: 'Molécula 1004',
    formula: 'Compound 1004',
    category: MoleculeCategory.ORGANIC,
    searchQuery: 'molecule 1004 3d',
    modelPath: '/models/1004-CPK-color-print_NIH3D.glb',
    description: 'Modelo molecular 3D real do NIH 3D Print Exchange.',
    modelVariants: {
      cpk: '/models/1004-CPK-color-print_NIH3D.glb',
      bas: '/models/1004-bas-color-print_NIH3D.glb',
      sticks: '/models/1004-sticks-color-vis_NIH3D.glb',
    },
  },
  {
    id: '3',
    name: 'Molécula 444539',
    formula: 'Compound 444539',
    category: MoleculeCategory.ORGANIC,
    searchQuery: 'molecule 444539 3d',
    modelPath: '/models/444539-CPK-color-print_NIH3D.glb',
    description: 'Modelo molecular 3D real do NIH 3D Print Exchange.',
    modelVariants: {
      cpk: '/models/444539-CPK-color-print_NIH3D.glb',
      bas: '/models/444539-bas-color-print_NIH3D.glb',
      sticks: '/models/444539-sticks-color-vis_NIH3D.glb',
    },
  },
  {
    id: '4',
    name: 'DNA',
    formula: 'Ácido Desoxirribonucleico',
    category: MoleculeCategory.BIOLOGICAL,
    searchQuery: 'DNA strand 3d',
    modelPath: '/models/dna.glb',
    description: 'O código genético de todos os organismos vivos.',
  },
  {
    id: '5',
    name: 'Glicose',
    formula: 'C₆H₁₂O₆',
    category: MoleculeCategory.ORGANIC,
    searchQuery: 'glucose molecule 3d',
    modelPath: '/models/glucose.glb',
    description: 'A principal fonte de energia para as células.',
  },
  {
    id: '6',
    name: 'Cafeína',
    formula: 'C₈H₁₀N₄O₂',
    category: MoleculeCategory.DRUG,
    searchQuery: 'caffeine molecule 3d',
    modelPath: '/models/caffeine.glb',
    description: 'O estimulante mais consumido no mundo.',
  },
  {
    id: '7',
    name: 'Metano',
    formula: 'CH₄',
    category: MoleculeCategory.ORGANIC,
    searchQuery: 'methane molecule 3d',
    modelPath: '/models/Metano-CPK-color-print_NIH3D.glb',
    description: 'O principal componente do gás natural.',
    modelVariants: {
      cpk: '/models/Metano-CPK-color-print_NIH3D.glb',
      bas: '/models/Metano-bas-color-print_NIH3D.glb',
      sticks: '/models/Metano-sticks-color-vis_NIH3D.glb',
    },
  },
  {
    id: '8',
    name: 'Hemoglobina',
    formula: 'Hb',
    category: MoleculeCategory.BIOLOGICAL,
    searchQuery: 'hemoglobin molecule 3d',
    modelPath: '/models/hemoglobin.glb',
    description: 'Transporta oxigênio no sangue.',
  },
  {
    id: '9',
    name: 'Dióxido de Carbono',
    formula: 'CO₂',
    category: MoleculeCategory.INORGANIC,
    searchQuery: 'carbon dioxide molecule 3d',
    modelPath: '/models/co2.glb',
    description: 'Gás essencial para a fotossíntese.',
  },
  {
    id: '10',
    name: 'Ácido Sulfúrico',
    formula: 'H₂SO₄',
    category: MoleculeCategory.INORGANIC,
    searchQuery: 'sulfuric acid molecule 3d',
    modelPath: '/models/sulfuric-acid.glb',
    description: 'Um ácido mineral forte e corrosivo.',
  },
  {
    id: '11',
    name: 'Benzeno',
    formula: 'C₆H₆',
    category: MoleculeCategory.ORGANIC,
    searchQuery: 'benzene molecule 3d',
    modelPath: '/models/benzene.glb',
    description: 'Um hidrocarboneto aromático importante.',
  },
  {
    id: '12',
    name: 'Aspirina',
    formula: 'C₉H₈O₄',
    category: MoleculeCategory.DRUG,
    searchQuery: 'aspirin molecule 3d',
    modelPath: '/models/aspirin.glb',
    description: 'Ácido acetilsalicílico, usado como analgésico.',
  },
  {
    id: '13',
    name: 'Neurônio (Célula)',
    formula: 'Célula',
    category: MoleculeCategory.BIOLOGICAL,
    searchQuery: 'neuron cell 3d',
    modelPath: '/models/neuron.glb',
    description: 'Estrutura celular do sistema nervoso.',
  },
  {
    id: '14',
    name: 'Vírus da Gripe',
    formula: 'Influenza',
    category: MoleculeCategory.BIOLOGICAL,
    searchQuery: 'influenza virus 3d',
    modelPath: '/models/influenza.glb',
    description: 'Vírus causador da gripe sazonal.',
  },
  {
    id: '15',
    name: 'Bulbasaur',
    formula: 'Pokémon #001',
    category: MoleculeCategory.BIOLOGICAL,
    searchQuery: 'bulbasaur 3d model',
    modelPath: '/models/bulbasaur.glb',
    description: 'Modelo 3D do Pokémon Bulbasaur - tipo Grama/Veneno.',
  }
];